package pl.futurecollars.invoice.model;

import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Invoice {

  @Setter
  @ApiModelProperty(value = "Invoice identification number (generated by application)", required = true, example = "1")
  private long id;

  @ApiModelProperty(value = "Date invoice was created", required = true)
  private LocalDate date;

  @ApiModelProperty(value = "Company who is selling the product/service", required = true)
  private Company seller;

  @ApiModelProperty(value = "Company who bought the product/service", required = true)
  private Company buyer;

  @ApiModelProperty(value = "List of products/services", required = true)
  private List<InvoiceEntry> invoiceEntries;

}
