/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package pl.futurecollars.invoicing;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import pl.futurecollars.invoicing.db.Database;
import pl.futurecollars.invoicing.db.memory.InMemoryDatabase;
import pl.futurecollars.invoicing.model.Company;
import pl.futurecollars.invoicing.model.Invoice;
import pl.futurecollars.invoicing.model.InvoiceEntry;
import pl.futurecollars.invoicing.model.Vat;
import pl.futurecollars.invoicing.service.InvoiceService;


public class App {

  public static void main(String[] args) {
      Database db = new InMemoryDatabase();
      InvoiceService service = new InvoiceService(db);

      Company companyBuyer = Company.builder()
          .name("Drutex")
          .taxIdentificationNumber(12345)
          .address("Warszawa ul.Nowa 2");

      Company.CompanyBuilder companySeller = Company.builder()
          .name("Polmos")
          .taxIdentificationNumber(42345)
          .address("Warszawa ul.Miła 42");

      //("5213861303", "ul. Bukowińska 24d/7 02-703 Warszawa, Polska", "iCode Trust Sp. z o.o");
  //    Company seller = new Company("552-168-66-00", "32-005 Niepolomice, Nagietkowa 19", "Piotr Kolacz Development");

      List<InvoiceEntry> products = List.of(new InvoiceEntry("Komputer", BigDecimal.valueOf(1000), BigDecimal.valueOf(230), Vat.VAT_23));


      Invoice.InvoiceBuilder invoice = Invoice.builder()
          .date(LocalDate.now())
          .fromCompany(companyBuyer)
          .toCompany(companySeller)
          .id()

          //    ., buyer, seller, products);

      int id = service.save(invoice);

      System.out.println(service.findForId(id));

      System.out.println(service.getAll());

      service.deleteInvoice(id);

  }
}
