name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Step 1 - Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - name: Step 2 - Build with Gradle
        run: ./gradlew build

      - name: Step 3 - Archive reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: build/reports/**
